
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READLINE = 20;
  public static final int DOUBLE = 4;
  public static final int NOTEQUAL = 29;
  public static final int GREATER = 32;
  public static final int PRIVATE = 25;
  public static final int CONTINUE = 27;
  public static final int INT = 3;
  public static final int MINUS = 40;
  public static final int LESS = 31;
  public static final int FOR = 10;
  public static final int STRINGCONST = 65;
  public static final int NOT = 35;
  public static final int AND = 34;
  public static final int READINTEGER = 19;
  public static final int HEXCONST = 63;
  public static final int MINUSASSIGN = 56;
  public static final int LESSEQUAL = 30;
  public static final int INTCONST = 62;
  public static final int PRODASSIGN = 54;
  public static final int RBRACES = 50;
  public static final int LBRACES = 49;
  public static final int DIVASSIGN = 53;
  public static final int OR = 36;
  public static final int COMMA = 44;
  public static final int BOOL = 5;
  public static final int DOUBLECONST = 64;
  public static final int CLASS = 7;
  public static final int DIV = 37;
  public static final int NEWARRAY = 17;
  public static final int ASSIGN = 42;
  public static final int IF = 12;
  public static final int THIS = 9;
  public static final int ID = 57;
  public static final int DOT = 48;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int EQUAL = 28;
  public static final int TRUE = 66;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int LCURLY = 51;
  public static final int LINE = 60;
  public static final int ADD = 39;
  public static final int NULL = 8;
  public static final int MOD = 41;
  public static final int BREAK = 15;
  public static final int VOID = 2;
  public static final int ERROR = 58;
  public static final int ADDASSIGN = 55;
  public static final int DTOI = 21;
  public static final int RCURLY = 52;
  public static final int LBRACK = 45;
  public static final int IMPORT = 59;
  public static final int GREATEREQUAL = 33;
  public static final int COLON = 43;
  public static final int ELSE = 13;
  public static final int FUNC = 61;
  public static final int RBRACK = 46;
  public static final int ITOD = 22;
  public static final int ITOB = 24;
  public static final int WHILE = 11;
  public static final int PUBLIC = 26;
  public static final int BTOI = 23;
  public static final int PROD = 38;
  public static final int STRING = 6;
  public static final int FALSE = 67;
  public static final int LRBRACK = 47;
  public static final int PRINT = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VOID",
  "INT",
  "DOUBLE",
  "BOOL",
  "STRING",
  "CLASS",
  "NULL",
  "THIS",
  "FOR",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "BREAK",
  "NEW",
  "NEWARRAY",
  "PRINT",
  "READINTEGER",
  "READLINE",
  "DTOI",
  "ITOD",
  "BTOI",
  "ITOB",
  "PRIVATE",
  "PUBLIC",
  "CONTINUE",
  "EQUAL",
  "NOTEQUAL",
  "LESSEQUAL",
  "LESS",
  "GREATER",
  "GREATEREQUAL",
  "AND",
  "NOT",
  "OR",
  "DIV",
  "PROD",
  "ADD",
  "MINUS",
  "MOD",
  "ASSIGN",
  "COLON",
  "COMMA",
  "LBRACK",
  "RBRACK",
  "LRBRACK",
  "DOT",
  "LBRACES",
  "RBRACES",
  "LCURLY",
  "RCURLY",
  "DIVASSIGN",
  "PRODASSIGN",
  "ADDASSIGN",
  "MINUSASSIGN",
  "ID",
  "ERROR",
  "IMPORT",
  "LINE",
  "FUNC",
  "INTCONST",
  "HEXCONST",
  "DOUBLECONST",
  "STRINGCONST",
  "TRUE",
  "FALSE"
  };
}

